version: '3' # DC Version.
services:
  web:
    build: . # Use the Dockerfile in this directory to build the image for this service.
    ports:
      - "${WEBAPP_PORT}:${WEBAPP_PORT}"
    volumes:
      - .:/src # Mounts the project directory (current directory) on the host to /code inside the container.
    environment:
      FLASK_ENV: development # Run in development mode and reload the code on change
  redis:
    image: "redis:alpine" # Pull a stock image to run Redis.
  db:
    image: postgres
    ports:
      - "${DB_PORT}:${DB_PORT}" # web’s application code could connect to the URL postgres://db:5432 and start using the Postgres database